### ISSUE TITLE
Lack of integration or acceptance tests/full scale examples

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation#111]
Hi, I am trying to get into using this library and have had some difficulties onboarding to it.
In many repositories, as I try to get into the flow of the code, I will use tests as reference/documentation for the workflows the library expects. In this library there are many unit tests which I have found to be valuable for getting to understand individual components; however, when I have scaled up to trying to piece larger chunks together I have run out of reference code.

For example, as part of my experimentation, I wanted to attempt and setup a Validator with the SeerCompiledRules.
My assumption for a quick test of what this would look like is:

```
Validator v = new Validator();
SeerCompiledRules scr = new SeerCompiledRules();
v.setCompiledRules(scr);

// blindly kept from the README.md
// except there is a typo in the README that says ValidatorServices instead
v.setValidatorId(ValidationServices.getInstance().getNextValidatorSequence());
v.setId("my-edits");

ValidationEngine ve = new ValidationEngine();
try {
	InitializationOptions options = new InitializationOptions();
      options.enableEngineStats();
	InitializationStats is = ValidationEngine.getInstance().initialize(options, v);
	System.out.println(ve.getStats());
	System.out.println("is0 :" + is.getNumEditsPreCompiled()); // prints 0 unexpectedly
	System.out.println("is1 :" + is.getNumEditsLoaded()); //prints 0 unexpectedly
	System.out.println("is2 :" + is.getNumEditsCompiled()); //print 0 as expected
	
	// but it also was {} for when I used the example from the README so maybe I misunderstood something
	System.out.println(ve.getValidators()); // prints {} unexpectedly

} catch (Exception e) {
	System.out.println("Caught error: " + e.getMessage());
}
```

Looking in the code I saw no examples of using a "real" CompiledRules object with a validator through to using the validator on example patient data. There are unit tests that use fake CompiledRules as part of loadValidatorFromXML, but never via setCompiledRules. 

I don't believe this particular omission is much of an issue, but I believe that in general the repository would benefit greatly from some End-to-End Tests or examples.

Hopefully if there is some code you had written while developing the library to make sure the end to end behavior works you could add it to the library for documentation. If existing code is not available if you could help me with my problem I would be happy to Pull Request a modified version into the library.

Happy for any help, advice or collaboration,
Thanks, James

**Comment by depryf** [comment]
Sounds good. 

Since I am not doing a good job of maintaining that other project (obviously), I think I will copy the two examples into this one, and maybe add a few more. I agree this will be a useful addition to this project. Thanks for pointing that out.

**Comment by jpalmerpivotal** [comment]
Thanks, looks to be working now. I am unblocked and making progress, will inform you if any more issues or questions pop up.
Thanks again!
