### ISSUE TITLE
N5036 bug, blank array shrinking causing false match

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation#117]
Hi Fabian,
In N5036 there is a bug when `AJCC TNM Clin N Suffix` or `AJCC TNM Path N Suffix` is all blank spaces.
What appears to happen is GEN_TO_STRING converts the char[5] `"     "` to a string `" "`. The `" "` is in the target value of `" (sn)"`. So it incorrectly returns true for `functions.GEN_AT(pnsuff, " (sn)") != 0`

Below is more context of the code

```
        functions.GEN_STRCPY(cnsuff, " ")
        functions.GEN_STRCAT(cnsuff, untrimmedline.ajccTnmClinNSuffix)
        functions.GEN_STRCPY(pnsuff, " ")
        functions.GEN_STRCAT(pnsuff, untrimmedline.ajccTnmPathNSuffix)
        
        if (functions.GEN_AT(cnsuff, " (sn)") != 0 || functions.GEN_AT(pnsuff, " (sn)") != 0) {
```
    
going into the GEN_AT code
    
    `String val = GEN_TO_STRING(value);`
  val = " ", value = char[5] ` , , , , `
  
  It seems to me that this is a behavior of toString(), but it would be a shame to lose that convenient functionality...
  
  We are also experiencing some other oddities around this edit but we believe that issue is on our side.
  
  Thanks, James.

**Comment by depryf** [comment]
Hi James,

I will take a closer look and try to reproduce using your example.

The tricky part with this type of tweaks (whatever it might be) is to make sure it doesn't affect anything else!

**Comment by depryf** [comment]
James, I cannot reproduce this problem.

I ran that edit (N5036) on the following data: 

```java
        Map<String, String> data = new HashMap<>();
        data.put("dateOfDiagnosis", "20210101");
        data.put("ajccId", "47");
        data.put("ajccTnmClinNSuffix", "(sn)");
        data.put("ajccTnmPathNSuffix", "    ");
        data.put("dateSentinelLymphNodeBiopsy", "        ");
        data.put("dateSentinelLymphNodeBiopsyFlag", "15");
```

And it properly failed in Genedits and for the translated version of the edit. 

If both suffixes are blank, then the edit passes in both. 

Could you please provide me the input values that behave differently in Genedits vs the translated edit?

**Comment by jpalmerpivotal** [comment]
I don't have it on me right now,  but I believe the input was:

data.put("dateOfDiagnosis", "20210831");
        data.put("ajccId", "48.2");
        data.put("ajccTnmClinNSuffix", " (f)");
        data.put("ajccTnmPathNSuffix", "    ");
        data.put("dateSentinelLymphNodeBiopsy", "");
        data.put("dateSentinelLymphNodeBiopsyFlag", "11");

**Comment by jpalmerpivotal** [comment]
Hi, got to my laptop today, and I think we may have been handling the blank wrong, we may have been passing in the " , , , " incorrectly and it was unclear in the char[] that is was ending. Need to debug more on my end. Closing this for now will reopen if we find it is a real issue.

**Comment by jpalmerpivotal** [comment]
Thanks again, we figured out the issue on our end, confusion around nulls. Their code defaulted the arrays to a ' ' and our code was getting passed there check of empties.
The edit has some bad logic in it. Your code is fine. I was incorrect about being 4 blanks due to poor displaying of the char[].

**Comment by depryf** [comment]
Sure. Great resolution, for me at least :-)

**Comment by jpalmerpivotal** [comment]
Pretty good on our end too,  provoked a good discussion on default values
and our data model.
