### ISSUE TITLE
Add method to calculate schema IDs

### ISSUE THREAD

**Issue by kirbykn** [imsweb/validation#118]
Add a class "ValidationStagingUtils". Add "computeCsSchemaId", "computeTnmSchemaId" and "computeEodSchemaId" methods. computeCsSchemaId will use the "getSsf25FromSex" logic that we have in SEER*DMS and SEER*Edits.

**Comment by kirbykn** [comment]
Since we wouldn't instantiate the utils class like we do for the context functions, the compute methods will need to have the staging instance passed in.

Also, should we do the "getSsf25FromSex" calculation in the computeCsSchemaId method, or will we use it before calling the compute method? @depryf

**Comment by depryf** [comment]
It sounds like splitting those into two methods is more flexible and won't prevent anything. I guess we should use two methods then.

**Comment by depryf** [comment]
I am not going to force a release for this. Other projects will use it when it becomes available.
