### ISSUE TITLE
Add support for new Genedits Functions

### ISSUE THREAD

**Issue by depryf** [imsweb/validation#15]
They added two new "lookup" methods. Need to look more into them and implement them in the context functions class.

**Comment by depryf** [comment]
@jlorentson, can you please provide the list of methods that this library doesn't currently implement? Thanks.

**Comment by jlorentson** [comment]
The two I see are:

int SQLLOOKUP( table_name, columns_list, search_for )
and
int SQLRANGELOOKUP( table_name, columns_list, search_for )


[SQLLOOKUPdescription.txt](https://github.com/imsweb/validation/files/1023025/SQLLOOKUPdescription.txt)
[SQLRANGELOOKUPdescription.txt](https://github.com/imsweb/validation/files/1023026/SQLRANGELOOKUPdescription.txt)

**Comment by depryf** [comment]
That's great, I knew it was going to be about lookup somehow. Please try to understand them (I am sure they must be somewhat similar to the existing ones) and see if you can implement them in Java.

**Comment by jlorentson** [comment]
@depryf The parameters passed to the methods include:
columns_list is a string containing the names of the column or columns to be searched. The Engine will prepare the query to concatenate the columns in the order in which they are listed in this parameter.
and
search_for is a string containing the value to be found. If columns_list identifies multiple columns, search_for must be assembled into a concatenated string that matches the order of the columns. 
What does that concatenation look like? should columns_list be a List<Object>, or a String, or what?

**Comment by depryf** [comment]
It looks to me our methods will need to take the following:
1. List<List<String>> table
2. List<String> columnNames
3. Object searchFor

We can't use a table name, we have to pass the full table to the method. The translation mechanism will replace the table name with the one that is actually added to the context of the edits. I am sure other lookup methods are already doing this.

The list should be the column headers, so the translation will have nothing to do there. 

You will need to call GEN_TO_STRING on the searchFor (it's standard practice for many translated methods), so it can handle a string vs a gString vs an array of characters, etc...

The method looks like it will be very simple to implement, although very inefficient compare to what they can do in SQL. You will use the first row of the table to get the column indexes to use. You will then go over each row, concatenate the values you need and compare to the provided value.

The result of the method should be "boolean". I know they use int but that's because they are in C world. We need to use boolean wherever we can, it fits better with edits.

I hope this all makes sense, let me know if it doesn't.

PS - one thing you will need to test is what happens when a bad column header is requested. No idea how they handle that (error, ignore the column, other?) but we have to implement the same behavior...

**Comment by jlorentson** [comment]
Sounds good. I expected the columnNames to be a list but wanted to confirm before getting too far afield.

Thanks.

**Comment by depryf** [comment]
Changes have been merged. Thanks!

Next step is to change the translation logic to properly translate calls to these new methods. But that will be handled in another project.
