### ISSUE TITLE
Convert sex to SSF25 for CS schema if SSF25 is missing

### ISSUE THREAD

**Issue by kirbykn** [imsweb/validation#24]
Peritoneum and Peritoneum Female Gen use sex as the discriminator for TNM and SSF25 as the discriminator for CS. If we can get the TNM schema and SSF25 is missing, convert the sex value so we can get the CS schema.

**Comment by depryf** [comment]
Please don't forget to add an entry in the CHANGELOG.MD file for your changes. Thanks.

**Comment by depryf** [comment]
These changes have been merged.
