### ISSUE TITLE
Changes for EOD in StagingContextFunctions

### ISSUE THREAD

**Issue by kirbykn** [imsweb/validation#42]
StagingContextFunctions has lists of constants and several context methods for CS and for TNM. We need the same for EOD.

Also, update the staging library to 3.x.

**Comment by kirbykn** [comment]
@depryf  We also want to add an '_eodSchemaId' value to the validatable right?

**Comment by depryf** [comment]
If we have it for CS and TNM, then I would say yes. We will have to remember to also add it to the validatable of other projects if the SEER edits rely on it.

**Comment by depryf** [comment]
This has been implemented.
