### ISSUE TITLE
Fix EOD field mapping

### ISSUE THREAD

**Issue by kirbykn** [imsweb/validation#44]
There are a few SSDI field names in the EOD mapping that don't match the NAACCR name.

sCategoryPathologic -> sCategoryPathological
lnStatusFemoralInguinalParaAorticAndPelvic -> lnStatusFemoralInguinalParaAorticPelvic
serumLdhPretreatmentLabValue -> ldhPretreatmentLabValue

**Comment by depryf** [comment]
@kirbykn can this issue be closed? It looks like you merged it already.
