### ISSUE TITLE
Stop setting eodSchemaId in the validatable

### ISSUE THREAD

**Issue by kirbykn** [imsweb/validation#75]
The EOD staging edits use the NAACCR fields 'schemaId' and 'ajccId', they don't use 'eodSchemaId'. We should stop setting it in the validatable and add a comment explaining why we have the CS/TNM schema IDs but not EOD. 

Should we run staging and set the schemaId and ajccId fields? In DMS (and soon to be Abs), those fields are not being set in the validatable.

**Comment by depryf** [comment]
I assume you are referencing the "SimpleNaaccrLinesValidatable". I am not against stopping writing the EOD schema, but you could also argue that the class is not DMS/Abs-specific and we are just assigning the three stating (CS, TNM and EOD) in specific variables, without assuming that specific projects use or don't use those variables in their edits. 

I would kind of lean towards leaving this in, even if we know none of our SEER projects use that specific EOD variables. I don't think it adds a lot of overhead to running edits.

I would certainly not compute the SCHEMA_ID and AJCC_ID; those are standard variables and we can't change any standard variables behind the scene. That would be very confusing. It is the caller's responsibility to compute those if needed.

**Comment by kirbykn** [comment]
Yes, I meant SimpleNaaccrLinesValidatable. I see how it makes sense to leave it in. I'm ok with closing this issue.
